destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/assets-pdf"
port: 4011
output: pdf
product: Assets
print_title: Assets documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: assets_sidebar
